object Versions {
    const val kotlin = "1.5.0"
    const val appCompat = "1.3.1"
    const val material = "1.4.0"
    const val constraintLayout = "2.1.0"
    const val jUnit = "4.13.2"
    const val ktxCore = "1.6.0"
    const val navVersion = "2.3.5"
    const val multidex = "2.0.1"
    const val okhttp: String = "4.7.2"
    const val coroutines: String = "1.3.9"
    const val room = "2.3.0"
    const val daggerHiltAndroid = "2.38.1"
    const val kotlinVersion: String = "1.4.31"
    const val testExt: String = "1.1.1"
    const val runner: String = "1.2.0"
    const val apollo: String = "2.4.6"
    const val lifecycleVersion = "2.4.0-alpha03"
}